version: '3.8'

services:
  lemmirun:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: lemmirun-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - lemmirun-network
    volumes:
      - ./logs:/app/logs

  nginx:
    image: nginx:alpine
    container_name: lemmirun-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - lemmirun
    restart: unless-stopped
    networks:
      - lemmirun-network

networks:
  lemmirun-network:
    driver: bridge

volumes:
  logs:
    driver: local